Added  filter dropdown for room types in AvailableClasses component
mahadihassanriyadh/chicken-coop pull request #20
Opened 2024-12-11 06:17 UTC by Chy-Zaber-Bin-Zahid

This pull request introduces a new feature to the AvailableClasses component: a filter dropdown that allows users to select between all classrooms, regular classrooms, or lab classrooms. This enhancement improves the user experience by providing more granular control over the displayed room options.

**Changes made:**
1. Added a new `selectedRoom` state variable to track the current filter selection.
2. Implemented a `handleRoomChange` function to update the filter state.
3. Modified the `handleOnSubmit` function to apply the selected filter when fetching results.
4. Added a new select element in the component's JSX for the filter options.
5. Updated the layout to accommodate the new filter dropdown alongside existing day and time selectors.

**Key features:**
- Users can now filter rooms by type: All Classrooms, Regular Classrooms, or Lab Classrooms.
- Lab rooms are identified by names ending with "L".
- The filtering logic is implemented efficiently within the existing `handleOnSubmit` function.

**Impact:**
This change does not affect the existing functionality but extends it. Users who don't use the filter will still see all available rooms as before.

**Testing:**
- Tested with various combinations of day, time, and filter selections to ensure correct results are displayed.
- Verified that the UI remains responsive and accessible with the addition of the new dropdown.

Please review and let me know if any further changes or clarifications are needed.

**After adding the new feature the ui/ux:**

![image](https://github.com/user-attachments/assets/8364f3fc-87d7-4fff-ad1d-87195d76a4e3)

2024-12-14 03:52 UTC, 0xriyadh requested changes
@Chy-Zaber-Bin-Zahid good job brother, please go through the suggestions and let me know if I can help you with anything.

2024-12-14 03:52 UTC, 0xriyadh commented on src/data/daysAndTimeSlots.js
> +export const roomOptions = [
I think `roomTypes` would be more appropriate naming instead of `roomOptions`

2024-12-14 03:52 UTC, 0xriyadh commented on src/data/daysAndTimeSlots.js
> +  { value: "Lab Classrooms", label: "Lab Classrooms" },
The `value` and `label` should not be same, the labels are good in your code. 
But for programmatic jobs we will use the `value` field, it's easier if that field is following `camelCasing` or `snake_casing` convention.

2024-12-14 03:52 UTC, 0xriyadh commented on src/Pages/AvailableClasses/AvailableClasses.js
> +    const [selectedRoom, setSelectedRoom] = useState("all");
maybe `selectedRoomType` is more appropriate

2024-12-16 04:36 UTC, Chy-Zaber-Bin-Zahid commented
I’ve made the necessary changes by updating the `value` field to `camelCase` for better programmatic usage and renamed the state variable to make it more meaningful and consistent. Let me know if further adjustments are needed. @0xriyadh

2024-12-16 08:17 UTC, 0xriyadh approved these changes
@Chy-Zaber-Bin-Zahid good job, merging it

2024-12-16 08:17 UTC, merged